version: 2.1
aliases:
  - &docker
    docker:
      - image: circleci/node:10
  - &attach_workspace
    - attach_workspace:
        at: .
jobs:
  build:
    <<: *docker
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build source
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - 'dist'
            - 'node_modules'
  lint:
    <<: *docker
    steps:
      - checkout
      - <<: *attach_workspace
      - run:
          name: Run lint
          command: npm run lint
  test:
    <<: *docker
    steps:
      - checkout
      - <<: *attach_workspace
      - run:
          name: Run tests
          command: node common/scripts/install-run-rush.js test --verbose
